[package]
name = "meshweaver"
version = "0.1.0"
edition = "2018"

[dependencies]
wgpu = "0.6"
winit = "0.23"
obj-rs = "0.6"
ultraviolet = "0.7"
bytemuck = { version = "1.4", features = ["derive"] }
pollster = "0.2"
